#!/bin/bash
#
# Build script to validate greenpithumb

# Exit build script on first failure
set -e

# Run unit tests and calculate code coverage.
coverage run \
  --source greenpithumb \
  --omit "greenpithumb/dht11/*" \
  -m unittest discover

# Run static analysis for Python bugs/cruft.
pyflakes greenpithumb/*.py tests/*.py

# Check that source has correct formatting.
DIFF=$(yapf \
  --diff \
  --recursive \
  --style google \
  ./ \
  --exclude "./greenpithumb/dht11/*" \
  --exclude "./third_party/*")
if [ -n "${DIFF}" ]; then
  echo "FAIL: Formatting does not match style:"
  echo "${DIFF}"
  exit 1
fi

# Check that docstrings are formatted correctly.
PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker \
  pylint --reports=n greenpithumb tests
